/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import java.util.Calendar;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Jair
 */
public class FrProjetoFinal extends javax.swing.JFrame {

    /**
     * Creates new form FrProjetoFinal
     */
    public FrProjetoFinal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        rbFem = new javax.swing.JCheckBox();
        rbMasc = new javax.swing.JCheckBox();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        btConsultar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        txtTituloNome = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea3.setBackground(new java.awt.Color(153, 0, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("nome");
        jScrollPane4.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 0, 204));

        txtNome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbFem);
        rbFem.setText("feminino");
        rbFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbMasc);
        rbMasc.setText("masculino");

        txtDia.setToolTipText("dia");
        txtDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaActionPerformed(evt);
            }
        });

        txtMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesActionPerformed(evt);
            }
        });

        btConsultar.setText("consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btLimpar.setText("limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        txtTituloNome.setEditable(false);
        txtTituloNome.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtTituloNome.setText("nome");

        txtTitulo.setEditable(false);
        txtTitulo.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        txtTitulo.setText("Guru On-line");
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtSexo.setEditable(false);
        txtSexo.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtSexo.setText("sexo");

        txtData.setEditable(false);
        txtData.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtData.setText("data de nascimento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAno))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(btConsultar))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btLimpar)
                                .addGap(255, 255, 255))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbFem)
                                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbMasc))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtTituloNome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 236, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTituloNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbFem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbMasc)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMes, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(txtDia)
                            .addComponent(txtAno))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btConsultar)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btLimpar)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesActionPerformed


    }//GEN-LAST:event_txtMesActionPerformed

    private void txtDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_txtDiaActionPerformed
    public void Nomear() {
        String nome;
        nome = txtNome.getText();
        if (nome.length() < 8) {
            JOptionPane.showMessageDialog(null, "legal se o seu nome fosse verdadeiro.");
        }
    }

    

    public void data() {
        Calendar hoje = Calendar.getInstance();
        int diaAtual, mesAtual, anoAtual;
        int diaNasc = Integer.parseInt(txtDia.getText());
        int mesNasc = Integer.parseInt(txtMes.getText());
        int anoNasc = Integer.parseInt(txtAno.getText());
        diaAtual = hoje.get(Calendar.DATE);
        mesAtual = hoje.get(Calendar.MONTH) + 1;
        anoAtual = hoje.get(Calendar.YEAR);
        int idade = anoAtual - anoNasc;

        if (mesAtual < mesNasc || (mesAtual == mesNasc && diaAtual < diaNasc)) {
            idade--;
        }
        String nome;
        nome = txtNome.getText();
        Random random = new Random();
        int numSorte = random.nextInt(100);
        int ano = Integer.parseInt(txtAno.getText());
        int Mes = Integer.parseInt(txtMes.getText());
        int dia = Integer.parseInt(txtDia.getText());
        if (Mes <= 0 || Mes >= 13) {
            JOptionPane.showMessageDialog(null, "insira um mes valido");
        } else {
            if (Mes == 4 || Mes == 6 || Mes == 9 || Mes == 11) {
                if (dia >= 31 || dia <= 0) {
                    JOptionPane.showMessageDialog(null, "insira uma dia valido");
                }
            }
            if (Mes == 2) {
                if (dia >= 30 || dia <= 0) {
                    JOptionPane.showMessageDialog(null, "insira uma dia valido");
                } else {
                    if (dia > 31 || dia <= 0) {
                        JOptionPane.showMessageDialog(null, "insira uma dia valido");

                    }
                }

            }

        }
        if (ano < 1900 || ano > 2024) {
            JOptionPane.showMessageDialog(null, "insira um ano valido");

        } else {
            if (Mes == 1) {
                if (dia >= 1 && dia <= 20) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo capricórcnio, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo capricórcnio, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }
                if (dia >= 21 && dia <= 31) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Aquário, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Aquário, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");

                    }
                }
            }

            if (Mes == 2) {
                if (dia >= 1 && dia <= 18) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Aquário, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Aquário, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }
                if (dia >= 19 && dia <= 29) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Peixes, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Peixes, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");

                    }
                }
            }

            if (Mes == 3) {
                if (dia >= 1 && dia <= 20) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Peixes, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Peixes, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }
                if (dia >= 21 && dia <= 31) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Áries, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Áries, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }

                }
            }
            if (Mes == 4) {
                if (dia >= 1 && dia <= 20) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Áries, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Áries, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }
                if (dia >= 21 && dia <= 30) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Touro, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Touro, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }

                }
            }
            if (Mes == 5) {
                if (dia >= 1 && dia <= 20) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Touro, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Touro, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }

                if (dia >= 21 && dia <= 31) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia" + dia + "-" + Mes + "-" + ano + " é do signo Gêmeos, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Gêmeos, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }

                }
            }
            if (Mes == 6) {
                if (dia >= 1 && dia <= 20) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Gêmeos, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Gêmeos, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }

                if (dia >= 21 && dia <= 30) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Câncer, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Câncer, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }

            }
            if (Mes == 7) {
                if (dia >= 1 && dia <= 22) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Câncer, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Câncer, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }

                if (dia >= 23 && dia <= 31) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Leão, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Leão, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }

                }
            }
            if (Mes == 8) {
                if (dia >= 1 && dia <= 22) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Leão, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");
                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Leão, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }
                if (dia >= 23 && dia <= 31) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Virgem, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");

                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Virgem, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }

            }
            if (Mes == 9) {
                if (dia >= 1 && dia <= 22) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Virgem, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");

                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Virgem, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }
                if (dia >= 23 && dia <= 30) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Libra, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");

                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Libra, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }

                }
            }
            if (Mes == 10) {
                if (dia >= 1 && dia <= 22) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Libra, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");

                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Libra, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }
                if (dia >= 23 && dia <= 31) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Escorpião, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");

                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Escorpião, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }

                }
            }
            if (Mes == 11) {
                if (dia >= 1 && dia <= 21) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Escorpião, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");

                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Escorpião, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }
                if (dia >= 22 && dia <= 30) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Sagitário, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");

                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Sagitário, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");

                    }
                }
            }
            if (Mes == 12) {
                if (dia >= 1 && dia <= 21) {
                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Sagitário, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");

                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascida no dia " + dia + "-" + Mes + "-" + ano + " é do signo Sagitário, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }
                if (dia >= 22 && dia <= 31) {

                    if (rbMasc.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sr." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Capricórcnio, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Verde.");

                    }
                    if (rbFem.isSelected()) {
                        JOptionPane.showMessageDialog(null, "Sra." + nome + ", nascido no dia " + dia + "-" + Mes + "-" + ano + " é do signo Capricórcnio, você tem " + idade + " anos - seu nº da sorte é " + numSorte + " e sua cor: Violeta.");
                    }
                }

            }

        }
    }

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        Nomear();
        data();
        int dia = Integer.parseInt(txtDia.getText());
        int mes = Integer.parseInt(txtMes.getText());
        int ano = Integer.parseInt(txtAno.getText());


    }//GEN-LAST:event_btConsultarActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void rbFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtNome.setText(null);
        txtDia.setText(null);
        txtMes.setText(null);
        txtAno.setText(null);
        rbMasc.setSelected(true);
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrProjetoFinal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrProjetoFinal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JCheckBox rbFem;
    private javax.swing.JCheckBox rbMasc;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTituloNome;
    // End of variables declaration//GEN-END:variables
}
